import numpy as np
import pandas as pd
import streamlit as st
import yfinance as yf

# 1. Page Configuration Setup
st.set_page_config(
    page_title="Quant Backtest Lab", page_icon="💻", layout="wide"
)

st.title("💻 Algorithmic Trading & Strategy Backtest Lab")
st.markdown(
    "Evaluate automated execution parameters based on native mathematical oscillator conditions."
)

# 2. Sidebar Control Interface
st.sidebar.header("Execution Inputs")
ticker = st.sidebar.text_input("Asset Ticker to Simulate", value="AAPL").upper()
days = st.sidebar.slider("Historical Testing Window (Days)", 30, 365, 180)

# Strategy Boundary Adjustments
rsi_lower = st.sidebar.slider("Oversold Entry Bound (Buy)", 10, 40, 30)
rsi_upper = st.sidebar.slider("Overbought Exit Bound (Sell)", 60, 90, 70)

if st.sidebar.button("Run Algorithmic Strategy Simulation"):
    with st.spinner("Downloading historical market data matrix..."):
        df = yf.download(ticker, period=f"{days}d")

    if df.empty:
        st.error(f"Execution Aborted: Zero-data vector returned for {ticker}")
    else:
        # Flatten multi-index columns if generated by yfinance API
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.droplevel(1)

        # ----------------------------------------------------
        # 3. NATIVE MATHEMATICAL RSI ENGINE
        # ----------------------------------------------------
        delta = df["Close"].diff()
        gain = delta.clip(lower=0)
        loss = -delta.clip(upper=0)

        # 14-period exponential smoothing formulas
        avg_gain = gain.ewm(com=13, adjust=False).mean()
        avg_loss = loss.ewm(com=13, adjust=False).mean()

        rs = avg_gain / avg_loss
        df["RSI"] = 100 - (100 / (1 + rs))

        # ----------------------------------------------------
        # 4. ALGORITHMIC TRADING SIMULATION LOOP
        # ----------------------------------------------------
        df = df.dropna().copy()

        # Track algorithmic system state parameters
        position = 0  # 0 = Cash, 1 = Long Asset position
        buy_prices = []
        sell_prices = []

        # Vector storage arrays for tracking portfolio value curves
        strategy_returns = []
        last_portfolio_value = 100.0  # Starting capital base standardized to $100

        # Calculate standard buy and hold return path for baseline comparison
        initial_price = df["Close"].iloc[0]
        df["Buy_And_Hold_Return"] = (df["Close"] / initial_price) * 100

        # Day-by-day historical state machine simulation loop
        for i in range(len(df)):
            current_close = df["Close"].iloc[i]
            current_rsi = df["RSI"].iloc[i]

            if i == 0:
                strategy_returns.append(last_portfolio_value)
                continue

            # Calculate today's value based on yesterday's positioning condition
            prev_close = df["Close"].iloc[i - 1]
            if position == 1:
                # If we are holding the stock, our capital moves with the asset price change
                daily_pct = (current_close - prev_close) / prev_close
                last_portfolio_value = last_portfolio_value * (1 + daily_pct)
            # If position == 0, we are holding cash, so portfolio value does not change

            strategy_returns.append(last_portfolio_value)

            # Algorithmic state checking logic
            if position == 0 and current_rsi < rsi_lower:
                # Trigger Buy Signal
                position = 1
                buy_prices.append((df.index[i], current_close))
            elif position == 1 and current_rsi > rsi_upper:
                # Trigger Sell Signal
                position = 0
                sell_prices.append((df.index[i], current_close))

        df["Strategy_Return"] = strategy_returns

        # ----------------------------------------------------
        # 5. UI RENDERING AND PERFORMANCE REPORTING
        # ----------------------------------------------------
        final_bh = df["Buy_And_Hold_Return"].iloc[-1] - 100
        final_strat = df["Strategy_Return"].iloc[-1] - 100

        col1, col2, col3 = st.columns(3)
        col1.metric(
            "Total Trades Executed",
            f"{len(buy_prices)} Buys / {len(sell_prices)} Sells",
        )
        col2.metric("Buy & Hold Return", f"{final_bh:+.2f}%")
        col3.metric(
            "RSI Strategy Return",
            f"{final_strat:+.2f}%",
            delta=f"{final_strat - final_bh:+.2f}% vs Benchmark",
        )

        # Plot performance baseline comparisons
        st.subheader("Performance Equity Curve: Strategy vs Benchmark")
        chart_df = pd.DataFrame(
            {
                "RSI Algorithmic Strategy": df["Strategy_Return"],
                "Buy & Hold Benchmark": df["Buy_And_Hold_Return"],
            },
            index=df.index,
        )
        st.line_chart(chart_df)

        # Technical details logs dropdown module
        with st.expander("Inspect Raw Backtesting Matrix Logs"):
            st.dataframe(
                df[["Close", "RSI", "Strategy_Return", "Buy_And_Hold_Return"]]
            )
print('bye')